---
title: Telugu Youtubers
author: "తులసీమోహన్"
date: "28-12-2023"
categories: [Telugu, Social, Code]
---

### VikramAdityaOfficial
- Owner      : Vikram Aditya
- Category   : Facts
- Description: Facts, Interestig topics, Mythology
- Subscribers:  2.21 M 
- Total views:  220 M 
- Started    : 2015
- Uploads    : 323
- Avg views/M: 3 M
- Income     : 100,000

### Prasad Tech in Telugu
- Owner      : Prasad Devarakonda
- Category   : Tech 
- Description: Mobile phone reviews, gadget reviews, tech news
- Subscribers: 4.33 M 
- Total views: 390 M  
- Started    : 2015
- Uploads    : 2800
- Avg views/M: 10 M
- Income     : 350,000

### Shanmukh Jaswanth
- Owner      : 
- Category   : Web series 
- Description: Software developer web series fame
- Subscribers:  4.97
- Total views:  460 M 
- Started    : 2013
- Uploads    : 87
- Avg views/M: 20 M
- Income     : 800,000


### Bayya Sunny Yadav
- Owner      : Sunny Yadav
- Category   : Moto vlogging
- Description: 
- Subscribers:  3.62 M 
- Total views:   130 M 
- Started    : 2017
- Uploads    : 343
- Avg views/M: 4 M
- Income     : 100000


### UNQ Gamer
- Owner      : Raju (Naga Raju) 
- Category   : Gaming
- Description: Fun and Entertainment, PubG 
- Subscribers: 1.77 M 
- Total views: 330 M 
- Started    : 2014
- Uploads    : 2000
- Avg views/M: 7 M 
- Income     : 300,000


### Vismai food
- Owner      : Teja Paruchuri
- Category   : Cooking
- Description: 
- Subscribers:  3.92 M
- Total views:   840 M 
- Started    : 2016
- Uploads    : 1000
- Avg views/M: 30 M 
- Income     : 500,000


### My Village show
- Owner      : Srikanth
- Category   : Entertainment
- Description: Funny potrails of village incidents.
- Subscribers:  2.81 M 
- Total views: 600 M   
- Started    : 2012
- Uploads    : 218
- Avg views/M: 10 M
- Income     : 300,000 


### Uma Telugu traveller
- Owner     : Uma Prasad
- Category  : Travel 
- Description: Travel vlog, 20 countries ,explores africa mostly  
- Subscribers:  965 K 
- Total views:  94 M  
- Started   : 2020
- Uploads   : 295
- Average Monthly views: 4 M
- Income    : 1,50,000


### Real Mysteries
- Owner : Prasanth
- Category : Mythology
- Description: Hindu Mythology, Current affairs, Social awareness
- Subscribers : 1.33 M 
- Total views :  170 M 
- Started : 2016
- Uploads : 150
- Average Monthly views: 4 M 
- Income : 100,000


### Fun pataaka
- Owner : A.R. Manohar 
- Cateogory : Pranks
- Description : 
- Subscribers : 1.11 M
- Total views : 150 M 
- Started : 2016 
- Uploads : 650
- Average Monthly views: 2 M 
- Income : 60,000



### Tej India 
- Owner      : Dora Sai Teja
- Category   : Web series
- Description: Misunderstandings, Back benchers famous shows
- Subscribers:  4.36 M  
- Total views: 190 M   
- Started    : 2016
- Uploads    : 90
- Avg views/M: 8 M
- Income     : 280,000 

#### Mahathalli 
- Owner      : Jahnavi Dasetty
- Category   : Orignal Content
- Description: Relatable content
- Subscribers: 2.04 M   
- Total views:  600 M 
- Started    : 2016
- Uploads    : 276
- Avg views/M: 5 M 
- Income     :  150,000

###  Chai Bisket
- Owner      : Anurag and  Sharat
- Category   : Original Content Media House
- Description:  
- Subscribers: 1 M   
- Total views: 120 M   
- Started    : 2016
- Uploads    : 219
- Avg views/M: 3 M
- Income     :  100,000

###  FACTS4U
- Owner      : 
- Category   : FACTS and opinions
- Description: A Research report on Current issues
- Subscribers: 728 K 
- Total views: 60 M   
- Started    : 2017
- Uploads    : 98
- Avg views/M: 1 M 
- Income     : 35,000

###  USA Raja Telugu Vlogs
- Owner      : Raja
- Category   : Lifestyle Vlogs
- Description: USA telugu vlogs 
- Subscribers: 3.25 M   
- Total views: 270 M    
- Started    : 2021
- Uploads    : 240 
- Avg views/M: 50 M
- Income     : 300,000 

###  Telugu Geeks
- Owner      :  
- Category   : Information  
- Description: Important points in famous books
- Subscribers: 1.69 M  
- Total views: 130 M   
- Started    : 2017
- Uploads    : 338
- Avg views/M: 2.5 M
- Income     : 85,000

###  Mehaboobdilse
- Owner      : Mehaboob big boss
- Category   : Entertainment
- Description: Web series,  
- Subscribers: 1.49 M   
- Total views: 130 M  
- Started    : 2012
- Uploads    : 
- Avg views/M: 5 M
- Income     : 150,000


###  Village Vihari
- Owner      : Shahid and Narendra
- Category   : History and Mystery
- Description: Adventures and Mysterious temples
- Subscribers:  1.2 M   
- Total views:  90 M   
- Started    : 2020
- Uploads    : 2016
- Avg views/M: 5 M 
- Income     : 1,50,000

###  Amma Chethi Vanta
- Owner      : Bhargavi 
- Category   : Cooking 
- Description: 
- Subscribers:  3.12 M 
- Total views:  620 M   
- Started    : 2017 
- Uploads    : 957  
- Avg views/M: 15 M
- Income     : 450,000

###  V R Facts in Telugu
- Owner      : Raju
- Category   : Facts
- Description: Interesting facts
- Subscribers: 1.5 M 
- Total views: 95 M    
- Started    : 2020
- Uploads    : 154
- Avg views/M: 5 M 
- Income     : 150,000

### Ravi Telugu Traveller
- Owner      : Ravi 
- Category   : Travel 
- Description: Travelled 186 countries
- Subscribers: 728 K 
- Total views: 70 M     
- Started    : 2020
- Uploads    : 330
- Avg views/M: 4 M 
- Income     : 1,20,000

### Telugu Badi 
- Owner      : Rama krishna 
- Category   : Facts
- Description: The video Encyclopaedia
- Subscribers:  2.16 M   
- Total views:  200 M  
- Started    : 2016
- Uploads    : 270
- Avg views/M: 2 M 
- Income     : 70,000

###  Naa Anveshana 
- Owner      : Anvesh
- Category   : Travel vlogs
- Description: 
- Subscribers: 1.9 M     
- Total views: 800 M    
- Started    : 2019 
- Uploads    : 722
- Avg views/M: 4 M
- Income     : 1,20,00

### Arun Surya Teja 
- Owner      : Arun Surya Teja  
- Category   : 
- Description: Research report on trnding Description
- Subscribers: 1.71 M   
- Total views: 170 M    
- Started    : 2016
- Uploads    : 160
- Avg views/M: 2.5 M
- Income     : 1,00,000

###  Creative Thinks
- Owner      : 
- Category   : Entertainment
- Description: Fun vidoes Village backdrop, Also has Creative thinks A to Z and Creative thinks Adventure  
- Subscribers: 2.37 M    
- Total views:  660 M   
- Started    : 2017
- Uploads    : 78
- Avg views/M: 8 M 
- Income     : 300,000

### Telugu Tech Tuts 
- Owner      : 
- Category   : Tech
- Description: Tech news, gadget reviews
- Subscribers:  1.74 M  
- Total views: 150 M    
- Started    : 2012
- Uploads    : 2200
- Avg views/M: 
- Income     : 120000


###  Vinay Kuyya 
- Owner      : Vinay Kuyya and Gopal
- Category   : Pranks
- Description: Does not seem to exist, Now there is Vinay Kuyya 01
- Subscribers: 422 K   
- Total views: 250 M    
- Started    : 2016
- Uploads    : 445
- Avg views/M: 5 M 
- Income     : 150,000

### Filmy Moji
- Owner      : Sai Kiran 
- Category   : Entertainment
- Description: Animated original content
- Subscribers: 4.54 M     
- Total views: 370 M   
- Started    : 2018
- Uploads    : 228 
- Avg views/M: 15 M
- Income     : 500,000

### Munna Bhai gaming
- Owner      : Venkata Achyut
- Category   : Gaming 
- Description: Streamer
- Subscribers: 3.24 M     
- Total views: 250 M   
- Started    : 2017
- Uploads    : 1000
- Avg views/M: 9 M
- Income     : 300,000

### Harsha Sai For U
- Owner      : Harsha Sai
- Category   : Give Away
- Description: Also has Hindi and Telugu channels
- Subscribers: 12.5 M (Hindi),  9.89 (Telugu)    
- Total views: 200 M   
- Started    : 2018
- Uploads    : 79
- Avg views/M: 10 M 
- Income     : 350,000

### Dhethadi
- Owner      : Harika
- Category   : Entertainment
- Description: Original content, Web Series 
- Subscribers: 2.1 M     
- Total views: 575 M   
- Started    : 2018
- Uploads    : 729
- Avg views/M: 13 M  
- Income     : 

### Bumchik Bunty
- Owner      : 
- Category   : Entertainment
- Description: Original contnet, Web Series
- Subscribers: 763 K     
- Total views: 229 M   
- Started    : 2017
- Uploads    : 452
- Avg views/M: 5 M 
- Income     : 

### Pakkinti Kurradu
- Handle     : @Pakkintikurraduu
- Owner      : 
- Category   : Entertainment
- Description: Original contnet, Web Series
- Subscribers: 1.34 M      
- Total views:  204 M
- Started    : 2017
- Uploads    : 420
- Avg views/M: 1.26 M  
- Income     : 

### Girl Formula
- Handle     : @GirlFormulabyChaiBisket
- Owner      : 
- Category   : Entertainment
- Description: Original contnet, Web Series
- Subscribers: 763 K     
- Total views: 229 M   
- Started    : 2017
- Uploads    : 452
- Avg views/M: 5 M 
- Income     : 



